version: "3.7"
services:
  logger:
    build:
      context: ./logger
    volumes:
      - ./logger:/scheduler/logger
      - /scheduler/logger/node_modules
      - /Users/shahiyar/Nivoda/scheduler/dbConfig:/scheduler/logger/config/dbConfig
    ports:
      - 3002:3002

  scheduler:
    build:
      context: ./Scheduler
    volumes:
      - ./Scheduler:/scheduler/Scheduler
      - /scheduler/Scheduler/node_modules
      -  /Users/shahiyar/Nivoda/scheduler/dbConfig:/scheduler/scheduler/config/dbConfig
    ports:
     - 3009:3000
    expose:
      - "3000"
    depends_on:
      - db
  db:
    platform: linux/x86_64
    build:
      context: ./db
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"

